# Generated by Django 3.0.5 on 2023-10-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
