# Generated by Django 3.0.5 on 2023-12-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231126_0137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='driver_status',
        ),
    ]
