# Generated by Django 3.0.5 on 2023-12-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.BigIntegerField(default=100),
        ),
    ]
