# Generated by Django 3.0.5 on 2023-12-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credit',
            field=models.BigIntegerField(default=10),
        ),
    ]
