# Generated by Django 3.0.5 on 2023-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20231202_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credit',
            field=models.BigIntegerField(default=100),
        ),
    ]
