# Generated by Django 5.0 on 2023-12-30 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_customuser_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hashtag', models.CharField(max_length=25)),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('Youtube', 'Youtube')], max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
