# Generated by Django 5.0 on 2023-12-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_depositemoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositemoney',
            name='method',
            field=models.CharField(choices=[('CREDIT_CARD', 'CREDIT_CARD'), ('DEBIT_CARD', 'DEBIT_CARD')], max_length=255),
        ),
        migrations.AlterField(
            model_name='depositemoney',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INPROCESS', 'INPROCESS'), ('DECLINED', 'DECLINED')], max_length=25),
        ),
    ]
