# Generated by Django 5.0 on 2024-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_customuser_id_alter_depositemoney_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Mobile_number',
            field=models.IntegerField(default=0),
        ),
    ]
