# Generated by Django 4.2.10 on 2024-02-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
